---
- :name: puppetmaster
  :basebox: centos68
  :bootstrap: centos68_puppetmaster.sh
  :aliases: 
    - puppet
    - puppetmaster.localdomain
    - puppetca.localdomain

- :name: v1-tes01
  :basebox: centos68
  :bootstrap: centos68.sh

- :name: v1-mqs01
  :basebox: rhel5.9 
  :bootstrap: rhel5.9_mq.sh

- :name: v1-jbo01
  :basebox: centos68 
  :bootstrap: centos68.sh 

